name: Run pytest on private repository
inputs:
  repo_name:
    description: 'Name of GitHub repo inside the kmiermans user'
    required: true
  secret:
    description: "Token to the repository being cloned + tested"
    required: true
runs:
  using: "composite"
  steps:
    # - name: Checkout private repo
    #   uses: actions/checkout@v2
    #   with:
    #     fetch-depth: "0"
    #     path: ${{ inputs.repo_name }}
    #     repository: kmiermans/${{ inputs.repo_name }}
    #     token: ${{ inputs.secret }}

    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        echo "dirs: "
        echo .* *

        python -m pip install --upgrade pip
        pip install pytest
      shell: bash

    - name: Test with pytest
      run: |
        pytest ${{ inputs.repo_name }}
      shell: bash

# name: 'Hello World'
# description: 'Greet someone'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
# runs:
#   using: "composite"
#   steps:
#     - run: echo Hello ${{ inputs.who-to-greet }}.
#       shell: bash
#     - id: random-number-generator
#       run: echo "::set-output name=random-id::$(echo $RANDOM)"
#       shell: bash
#     - run: ${{ github.action_path }}/run.sh
#       shell: bash

