name: Run pytest on private repository
inputs:
  repo_name:
    description: 'Name of GitHub repo inside the kmiermans user'
    required: true
  secret:
    description: "Token to the repository being cloned + tested"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

        pip install "${{ inputs.repo_name }}/.[dev, options]"
      shell: bash

    - name: Test with pytest
      run: |
        pytest ${{ inputs.repo_name }}
      shell: bash